FROM container-registry.oracle.com/database/free:23.26.0.0

# Create volume for Oracle data
VOLUME /opt/oracle/oradata

# It is handled in the docker-compose file. EXPOSE is deprecated
# EXPOSE 1521

# CMD [ "oracle" ]